### ISSUE TITLE
macOS

### ISSUE THREAD

**Issue by marekkowalczyk** [nezaboodka/nevod#1]
``negrep`` build for macOS?

**Comment by doidor** [comment]
You can build for MacOS by installing [dotnet core](https://dotnet.microsoft.com/download) and then:

```
chmod a+x ./Deployment/publish_osx_local.sh
./Deployment/publish_osx_local.sh
```

**Comment by dmitry-surkov** [comment]
The workflow has been changed to build Negrep for macOS. The negrep for macOS is already available in Release artefacts: https://github.com/nezaboodka/nevod/releases/tag/v1.1.6. 

The https://nevod.io site was updated to provides downloading link to Negrep for macOS.
